version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: discord-clone
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://postgres.knsvnppirekypcqsnxya:tiquZJp5hCTiV0cN@aws-0-eu-central-1.pooler.supabase.com:6543/postgres?pgbouncer=true&connection_limit=1
      DIRECT_URL: postgres://postgres.knsvnppirekypcqsnxya:tiquZJp5hCTiV0cN@aws-0-eu-central-1.pooler.supabase.com:5432/postgres
    depends_on:
      - db

  db:
    image: postgres:14
    container_name: discord-clone-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
